# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tryui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(210, 210))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clientLabel = QtWidgets.QLabel(self.frame_5)
        self.clientLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clientLabel.setObjectName("clientLabel")
        self.horizontalLayout.addWidget(self.clientLabel)
        self.clientResultLabel = QtWidgets.QLabel(self.frame_5)
        self.clientResultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clientResultLabel.setObjectName("clientResultLabel")
        self.horizontalLayout.addWidget(self.clientResultLabel)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.searchForClientButton = QtWidgets.QPushButton(self.tab_6)
        self.searchForClientButton.setObjectName("searchForClientButton")
        self.gridLayout_3.addWidget(self.searchForClientButton, 1, 4, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.tab_6)
        self.tableView_2.setSortingEnabled(True)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_3.addWidget(self.tableView_2, 0, 1, 1, 4)
        self.searchClientsByNIPButton = QtWidgets.QPushButton(self.tab_6)
        self.searchClientsByNIPButton.setObjectName("searchClientsByNIPButton")
        self.gridLayout_3.addWidget(self.searchClientsByNIPButton, 1, 1, 1, 1)
        self.searchClientByCodeButton = QtWidgets.QPushButton(self.tab_6)
        self.searchClientByCodeButton.setObjectName("searchClientByCodeButton")
        self.gridLayout_3.addWidget(self.searchClientByCodeButton, 1, 2, 1, 1)
        self.searchClientsByCityButton = QtWidgets.QPushButton(self.tab_6)
        self.searchClientsByCityButton.setObjectName("searchClientsByCityButton")
        self.gridLayout_3.addWidget(self.searchClientsByCityButton, 1, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.searchItemByCodeButton = QtWidgets.QPushButton(self.tab_5)
        self.searchItemByCodeButton.setObjectName("searchItemByCodeButton")
        self.gridLayout_10.addWidget(self.searchItemByCodeButton, 1, 4, 1, 1)
        self.searchItemsByCityButton = QtWidgets.QPushButton(self.tab_5)
        self.searchItemsByCityButton.setObjectName("searchItemsByCityButton")
        self.gridLayout_10.addWidget(self.searchItemsByCityButton, 1, 3, 1, 1)
        self.searchItemByGroupButton = QtWidgets.QPushButton(self.tab_5)
        self.searchItemByGroupButton.setObjectName("searchItemByGroupButton")
        self.gridLayout_10.addWidget(self.searchItemByGroupButton, 1, 5, 1, 1)
        self.searchForItemButton = QtWidgets.QPushButton(self.tab_5)
        self.searchForItemButton.setObjectName("searchForItemButton")
        self.gridLayout_10.addWidget(self.searchForItemButton, 1, 6, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_5)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setIconSize(QtCore.QSize(50, 50))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_10.addWidget(self.tableView, 0, 3, 1, 4)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 0, 0, 1, 3)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 8, 2)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.generateInvoiceButton = QtWidgets.QPushButton(self.frame_6)
        self.generateInvoiceButton.setObjectName("generateInvoiceButton")
        self.gridLayout_11.addWidget(self.generateInvoiceButton, 3, 0, 1, 2)
        self.nettoAmountLabel = QtWidgets.QLabel(self.frame_6)
        self.nettoAmountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountLabel.setObjectName("nettoAmountLabel")
        self.gridLayout_11.addWidget(self.nettoAmountLabel, 1, 0, 1, 1)
        self.nettoAmountResultLabel = QtWidgets.QLabel(self.frame_6)
        self.nettoAmountResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountResultLabel.setObjectName("nettoAmountResultLabel")
        self.gridLayout_11.addWidget(self.nettoAmountResultLabel, 1, 1, 1, 1)
        self.totalAmountLabel = QtWidgets.QLabel(self.frame_6)
        self.totalAmountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountLabel.setObjectName("totalAmountLabel")
        self.gridLayout_11.addWidget(self.totalAmountLabel, 2, 0, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(self.frame_6)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_11.addWidget(self.tableView_3, 0, 0, 1, 2)
        self.totalAmountResultLabel = QtWidgets.QLabel(self.frame_6)
        self.totalAmountResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountResultLabel.setObjectName("totalAmountResultLabel")
        self.gridLayout_11.addWidget(self.totalAmountResultLabel, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 8, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setObjectName("frame_4")
        self.discountLabel = QtWidgets.QLabel(self.frame_4)
        self.discountLabel.setGeometry(QtCore.QRect(9, 96, 32, 16))
        self.discountLabel.setObjectName("discountLabel")
        self.discountSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.discountSpinBox.setGeometry(QtCore.QRect(9, 115, 37, 20))
        self.discountSpinBox.setObjectName("discountSpinBox")
        self.invoiceGenerationDateLabel = QtWidgets.QLabel(self.frame_4)
        self.invoiceGenerationDateLabel.setGeometry(QtCore.QRect(9, 141, 89, 16))
        self.invoiceGenerationDateLabel.setObjectName("invoiceGenerationDateLabel")
        self.invoiceGenerationDateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.invoiceGenerationDateEdit.setGeometry(QtCore.QRect(9, 160, 81, 20))
        self.invoiceGenerationDateEdit.setObjectName("invoiceGenerationDateEdit")
        self.invoiceGenerationDateLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.invoiceGenerationDateLabel_2.setGeometry(QtCore.QRect(9, 186, 73, 16))
        self.invoiceGenerationDateLabel_2.setObjectName("invoiceGenerationDateLabel_2")
        self.invoicePaymentDateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.invoicePaymentDateEdit.setGeometry(QtCore.QRect(9, 205, 81, 20))
        self.invoicePaymentDateEdit.setDate(QtCore.QDate(2020, 1, 10))
        self.invoicePaymentDateEdit.setObjectName("invoicePaymentDateEdit")
        self.invoiceNumberEdit = QtWidgets.QLineEdit(self.frame_4)
        self.invoiceNumberEdit.setGeometry(QtCore.QRect(9, 28, 133, 20))
        self.invoiceNumberEdit.setObjectName("invoiceNumberEdit")
        self.invoiceNumberLabel = QtWidgets.QLabel(self.frame_4)
        self.invoiceNumberLabel.setGeometry(QtCore.QRect(9, 9, 55, 16))
        self.invoiceNumberLabel.setObjectName("invoiceNumberLabel")
        self.invoiceSaleDateLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.invoiceSaleDateLabel_3.setGeometry(QtCore.QRect(9, 231, 79, 16))
        self.invoiceSaleDateLabel_3.setObjectName("invoiceSaleDateLabel_3")
        self.invoiceSaleDateEdit_2 = QtWidgets.QDateEdit(self.frame_4)
        self.invoiceSaleDateEdit_2.setGeometry(QtCore.QRect(9, 250, 81, 20))
        self.invoiceSaleDateEdit_2.setDate(QtCore.QDate(2020, 1, 10))
        self.invoiceSaleDateEdit_2.setObjectName("invoiceSaleDateEdit_2")
        self.invoicTypeLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.invoicTypeLabel_2.setGeometry(QtCore.QRect(148, 9, 56, 16))
        self.invoicTypeLabel_2.setObjectName("invoicTypeLabel_2")
        self.invoiceTypeComboBox = QtWidgets.QComboBox(self.frame_4)
        self.invoiceTypeComboBox.setGeometry(QtCore.QRect(148, 28, 67, 20))
        self.invoiceTypeComboBox.setObjectName("invoiceTypeComboBox")
        self.invoiceTypeComboBox.addItem("")
        self.invoiceTypeComboBox.addItem("")
        self.invoiceTypeComboBox.addItem("")
        self.invoiceTypeComboBox.addItem("")
        self.invoicTypeLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.invoicTypeLabel_3.setGeometry(QtCore.QRect(148, 54, 78, 16))
        self.invoicTypeLabel_3.setObjectName("invoicTypeLabel_3")
        self.invoiceTypeComboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.invoiceTypeComboBox_2.setGeometry(QtCore.QRect(148, 73, 42, 20))
        self.invoiceTypeComboBox_2.setObjectName("invoiceTypeComboBox_2")
        self.invoiceTypeComboBox_2.addItem("")
        self.invoiceTypeComboBox_2.addItem("")
        self.invoiceTypeComboBox_2.addItem("")
        self.warehouseSelectLabel_4 = QtWidgets.QLabel(self.frame_4)
        self.warehouseSelectLabel_4.setGeometry(QtCore.QRect(148, 99, 47, 16))
        self.warehouseSelectLabel_4.setObjectName("warehouseSelectLabel_4")
        self.warehouseSelectComboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.warehouseSelectComboBox_3.setGeometry(QtCore.QRect(148, 118, 32, 20))
        self.warehouseSelectComboBox_3.setObjectName("warehouseSelectComboBox_3")
        self.warehouseSelectComboBox_3.addItem("")
        self.warehouseSelectComboBox_3.addItem("")
        self.warehouseSelectComboBox_3.addItem("")
        self.warehouseSelectLabel_5 = QtWidgets.QLabel(self.frame_4)
        self.warehouseSelectLabel_5.setGeometry(QtCore.QRect(148, 144, 65, 16))
        self.warehouseSelectLabel_5.setObjectName("warehouseSelectLabel_5")
        self.warehouseSelectComboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.warehouseSelectComboBox_4.setGeometry(QtCore.QRect(148, 163, 70, 20))
        self.warehouseSelectComboBox_4.setObjectName("warehouseSelectComboBox_4")
        self.warehouseSelectComboBox_4.addItem("")
        self.warehouseSelectComboBox_4.addItem("")
        self.priceTypeLabel = QtWidgets.QLabel(self.frame_4)
        self.priceTypeLabel.setGeometry(QtCore.QRect(148, 189, 57, 16))
        self.priceTypeLabel.setObjectName("priceTypeLabel")
        self.priceTypeComboBox = QtWidgets.QComboBox(self.frame_4)
        self.priceTypeComboBox.setGeometry(QtCore.QRect(148, 208, 75, 20))
        self.priceTypeComboBox.setObjectName("priceTypeComboBox")
        self.priceTypeComboBox.addItem("")
        self.priceTypeComboBox.addItem("")
        self.paymentComboBox = QtWidgets.QComboBox(self.frame_4)
        self.paymentComboBox.setGeometry(QtCore.QRect(148, 253, 68, 20))
        self.paymentComboBox.setObjectName("paymentComboBox")
        self.paymentComboBox.addItem("")
        self.paymentComboBox.addItem("")
        self.paymentComboBox.addItem("")
        self.paymentLabel = QtWidgets.QLabel(self.frame_4)
        self.paymentLabel.setGeometry(QtCore.QRect(148, 234, 45, 16))
        self.paymentLabel.setObjectName("paymentLabel")
        self.discountLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.discountLabel_3.setGeometry(QtCore.QRect(10, 51, 71, 16))
        self.discountLabel_3.setObjectName("discountLabel_3")
        self.accountingNumberSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.accountingNumberSpinBox.setGeometry(QtCore.QRect(10, 70, 37, 20))
        self.accountingNumberSpinBox.setObjectName("accountingNumberSpinBox")
        self.gridLayout_4.addWidget(self.frame_4, 8, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.sortInvoicesPushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.sortInvoicesPushButton_5.setObjectName("sortInvoicesPushButton_5")
        self.gridLayout_7.addWidget(self.sortInvoicesPushButton_5, 2, 0, 1, 1)
        self.tableView_4 = QtWidgets.QTableView(self.frame_3)
        self.tableView_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_4.setIconSize(QtCore.QSize(50, 50))
        self.tableView_4.setSortingEnabled(True)
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_4.horizontalHeader().setStretchLastSection(True)
        self.tableView_4.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_7.addWidget(self.tableView_4, 1, 0, 1, 4)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.documentsTypeComboBox = QtWidgets.QComboBox(self.frame_3)
        self.documentsTypeComboBox.setObjectName("documentsTypeComboBox")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.gridLayout_7.addWidget(self.documentsTypeComboBox, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_2 = QtWidgets.QFrame(self.tab_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clientLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.clientLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clientLabel_2.setObjectName("clientLabel_2")
        self.horizontalLayout_2.addWidget(self.clientLabel_2)
        self.clientResultLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.clientResultLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.clientResultLabel_2.setObjectName("clientResultLabel_2")
        self.horizontalLayout_2.addWidget(self.clientResultLabel_2)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.frame_7)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.searchForClientButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.searchForClientButton_2.setObjectName("searchForClientButton_2")
        self.gridLayout_13.addWidget(self.searchForClientButton_2, 1, 4, 1, 1)
        self.tableView_5 = QtWidgets.QTableView(self.tab_7)
        self.tableView_5.setSortingEnabled(True)
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_5.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_13.addWidget(self.tableView_5, 0, 1, 1, 4)
        self.searchClientsByNIPButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.searchClientsByNIPButton_2.setObjectName("searchClientsByNIPButton_2")
        self.gridLayout_13.addWidget(self.searchClientsByNIPButton_2, 1, 1, 1, 1)
        self.searchClientByCodeButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.searchClientByCodeButton_2.setObjectName("searchClientByCodeButton_2")
        self.gridLayout_13.addWidget(self.searchClientByCodeButton_2, 1, 2, 1, 1)
        self.searchClientsByCityButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.searchClientsByCityButton_2.setObjectName("searchClientsByCityButton_2")
        self.gridLayout_13.addWidget(self.searchClientsByCityButton_2, 1, 3, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.searchItemByCodeButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.searchItemByCodeButton_2.setObjectName("searchItemByCodeButton_2")
        self.gridLayout_14.addWidget(self.searchItemByCodeButton_2, 1, 4, 1, 1)
        self.searchItemsByCityButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.searchItemsByCityButton_2.setObjectName("searchItemsByCityButton_2")
        self.gridLayout_14.addWidget(self.searchItemsByCityButton_2, 1, 3, 1, 1)
        self.searchItemByGroupButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.searchItemByGroupButton_2.setObjectName("searchItemByGroupButton_2")
        self.gridLayout_14.addWidget(self.searchItemByGroupButton_2, 1, 5, 1, 1)
        self.searchForItemButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.searchForItemButton_2.setObjectName("searchForItemButton_2")
        self.gridLayout_14.addWidget(self.searchForItemButton_2, 1, 6, 1, 1)
        self.tableView_6 = QtWidgets.QTableView(self.tab_8)
        self.tableView_6.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_6.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_6.setIconSize(QtCore.QSize(50, 50))
        self.tableView_6.setSortingEnabled(True)
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_6.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_6.horizontalHeader().setStretchLastSection(True)
        self.tableView_6.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_14.addWidget(self.tableView_6, 0, 3, 1, 4)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.gridLayout_12.addWidget(self.tabWidget_3, 0, 0, 1, 3)
        self.gridLayout_9.addWidget(self.frame_7, 0, 0, 8, 2)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.generateInvoiceButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.generateInvoiceButton_2.setObjectName("generateInvoiceButton_2")
        self.gridLayout_15.addWidget(self.generateInvoiceButton_2, 3, 0, 1, 2)
        self.nettoAmountLabel_2 = QtWidgets.QLabel(self.frame_8)
        self.nettoAmountLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountLabel_2.setObjectName("nettoAmountLabel_2")
        self.gridLayout_15.addWidget(self.nettoAmountLabel_2, 1, 0, 1, 1)
        self.nettoAmountResultLabel_2 = QtWidgets.QLabel(self.frame_8)
        self.nettoAmountResultLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountResultLabel_2.setObjectName("nettoAmountResultLabel_2")
        self.gridLayout_15.addWidget(self.nettoAmountResultLabel_2, 1, 1, 1, 1)
        self.totalAmountLabel_2 = QtWidgets.QLabel(self.frame_8)
        self.totalAmountLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountLabel_2.setObjectName("totalAmountLabel_2")
        self.gridLayout_15.addWidget(self.totalAmountLabel_2, 2, 0, 1, 1)
        self.tableView_7 = QtWidgets.QTableView(self.frame_8)
        self.tableView_7.setObjectName("tableView_7")
        self.gridLayout_15.addWidget(self.tableView_7, 0, 0, 1, 2)
        self.totalAmountResultLabel_2 = QtWidgets.QLabel(self.frame_8)
        self.totalAmountResultLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountResultLabel_2.setObjectName("totalAmountResultLabel_2")
        self.gridLayout_15.addWidget(self.totalAmountResultLabel_2, 2, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 8, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setObjectName("frame_9")
        self.discountLabel_2 = QtWidgets.QLabel(self.frame_9)
        self.discountLabel_2.setGeometry(QtCore.QRect(9, 54, 32, 16))
        self.discountLabel_2.setObjectName("discountLabel_2")
        self.discountSpinBox_2 = QtWidgets.QSpinBox(self.frame_9)
        self.discountSpinBox_2.setGeometry(QtCore.QRect(9, 73, 37, 20))
        self.discountSpinBox_2.setObjectName("discountSpinBox_2")
        self.invoiceGenerationDateLabel_3 = QtWidgets.QLabel(self.frame_9)
        self.invoiceGenerationDateLabel_3.setGeometry(QtCore.QRect(9, 99, 89, 16))
        self.invoiceGenerationDateLabel_3.setObjectName("invoiceGenerationDateLabel_3")
        self.invoiceGenerationDateEdit_2 = QtWidgets.QDateEdit(self.frame_9)
        self.invoiceGenerationDateEdit_2.setGeometry(QtCore.QRect(9, 118, 81, 20))
        self.invoiceGenerationDateEdit_2.setObjectName("invoiceGenerationDateEdit_2")
        self.invoiceGenerationDateLabel_4 = QtWidgets.QLabel(self.frame_9)
        self.invoiceGenerationDateLabel_4.setGeometry(QtCore.QRect(9, 144, 73, 16))
        self.invoiceGenerationDateLabel_4.setObjectName("invoiceGenerationDateLabel_4")
        self.invoicePaymentDateEdit_2 = QtWidgets.QDateEdit(self.frame_9)
        self.invoicePaymentDateEdit_2.setGeometry(QtCore.QRect(9, 163, 81, 20))
        self.invoicePaymentDateEdit_2.setDate(QtCore.QDate(2020, 1, 10))
        self.invoicePaymentDateEdit_2.setObjectName("invoicePaymentDateEdit_2")
        self.invoiceNumberEdit_2 = QtWidgets.QLineEdit(self.frame_9)
        self.invoiceNumberEdit_2.setGeometry(QtCore.QRect(9, 28, 133, 20))
        self.invoiceNumberEdit_2.setObjectName("invoiceNumberEdit_2")
        self.invoiceNumberLabel_2 = QtWidgets.QLabel(self.frame_9)
        self.invoiceNumberLabel_2.setGeometry(QtCore.QRect(9, 9, 55, 16))
        self.invoiceNumberLabel_2.setObjectName("invoiceNumberLabel_2")
        self.invoiceSaleDateLabel_4 = QtWidgets.QLabel(self.frame_9)
        self.invoiceSaleDateLabel_4.setGeometry(QtCore.QRect(9, 189, 79, 16))
        self.invoiceSaleDateLabel_4.setObjectName("invoiceSaleDateLabel_4")
        self.invoiceSaleDateEdit_3 = QtWidgets.QDateEdit(self.frame_9)
        self.invoiceSaleDateEdit_3.setGeometry(QtCore.QRect(9, 208, 81, 20))
        self.invoiceSaleDateEdit_3.setDate(QtCore.QDate(2020, 1, 10))
        self.invoiceSaleDateEdit_3.setObjectName("invoiceSaleDateEdit_3")
        self.invoicTypeLabel_4 = QtWidgets.QLabel(self.frame_9)
        self.invoicTypeLabel_4.setGeometry(QtCore.QRect(148, 9, 56, 16))
        self.invoicTypeLabel_4.setObjectName("invoicTypeLabel_4")
        self.invoiceTypeComboBox_3 = QtWidgets.QComboBox(self.frame_9)
        self.invoiceTypeComboBox_3.setGeometry(QtCore.QRect(148, 28, 67, 20))
        self.invoiceTypeComboBox_3.setObjectName("invoiceTypeComboBox_3")
        self.invoiceTypeComboBox_3.addItem("")
        self.invoiceTypeComboBox_3.addItem("")
        self.invoiceTypeComboBox_3.addItem("")
        self.invoicTypeLabel_5 = QtWidgets.QLabel(self.frame_9)
        self.invoicTypeLabel_5.setGeometry(QtCore.QRect(148, 54, 78, 16))
        self.invoicTypeLabel_5.setObjectName("invoicTypeLabel_5")
        self.invoiceTypeComboBox_4 = QtWidgets.QComboBox(self.frame_9)
        self.invoiceTypeComboBox_4.setGeometry(QtCore.QRect(148, 73, 42, 20))
        self.invoiceTypeComboBox_4.setObjectName("invoiceTypeComboBox_4")
        self.invoiceTypeComboBox_4.addItem("")
        self.invoiceTypeComboBox_4.addItem("")
        self.invoiceTypeComboBox_4.addItem("")
        self.warehouseSelectLabel_6 = QtWidgets.QLabel(self.frame_9)
        self.warehouseSelectLabel_6.setGeometry(QtCore.QRect(148, 99, 47, 16))
        self.warehouseSelectLabel_6.setObjectName("warehouseSelectLabel_6")
        self.warehouseSelectComboBox_5 = QtWidgets.QComboBox(self.frame_9)
        self.warehouseSelectComboBox_5.setGeometry(QtCore.QRect(148, 118, 32, 20))
        self.warehouseSelectComboBox_5.setObjectName("warehouseSelectComboBox_5")
        self.warehouseSelectComboBox_5.addItem("")
        self.warehouseSelectComboBox_5.addItem("")
        self.warehouseSelectComboBox_5.addItem("")
        self.warehouseSelectLabel_7 = QtWidgets.QLabel(self.frame_9)
        self.warehouseSelectLabel_7.setGeometry(QtCore.QRect(148, 144, 65, 16))
        self.warehouseSelectLabel_7.setObjectName("warehouseSelectLabel_7")
        self.warehouseSelectComboBox_6 = QtWidgets.QComboBox(self.frame_9)
        self.warehouseSelectComboBox_6.setGeometry(QtCore.QRect(148, 163, 70, 20))
        self.warehouseSelectComboBox_6.setObjectName("warehouseSelectComboBox_6")
        self.warehouseSelectComboBox_6.addItem("")
        self.warehouseSelectComboBox_6.addItem("")
        self.priceTypeLabel_2 = QtWidgets.QLabel(self.frame_9)
        self.priceTypeLabel_2.setGeometry(QtCore.QRect(148, 189, 57, 16))
        self.priceTypeLabel_2.setObjectName("priceTypeLabel_2")
        self.priceTypeComboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.priceTypeComboBox_2.setGeometry(QtCore.QRect(148, 208, 75, 20))
        self.priceTypeComboBox_2.setObjectName("priceTypeComboBox_2")
        self.priceTypeComboBox_2.addItem("")
        self.priceTypeComboBox_2.addItem("")
        self.paymentComboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.paymentComboBox_2.setGeometry(QtCore.QRect(148, 253, 68, 20))
        self.paymentComboBox_2.setObjectName("paymentComboBox_2")
        self.paymentComboBox_2.addItem("")
        self.paymentComboBox_2.addItem("")
        self.paymentComboBox_2.addItem("")
        self.paymentLabel_2 = QtWidgets.QLabel(self.frame_9)
        self.paymentLabel_2.setGeometry(QtCore.QRect(148, 234, 45, 16))
        self.paymentLabel_2.setObjectName("paymentLabel_2")
        self.gridLayout_9.addWidget(self.frame_9, 8, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbouy = QtWidgets.QMenu(self.menubar)
        self.menuAbouy.setObjectName("menuAbouy")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbouy.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clientLabel.setText(_translate("MainWindow", "Client:"))
        self.clientResultLabel.setText(_translate("MainWindow", "Not selected yet"))
        self.searchForClientButton.setText(_translate("MainWindow", "Search by Name"))
        self.searchClientsByNIPButton.setText(_translate("MainWindow", "Search by NIP"))
        self.searchClientByCodeButton.setText(_translate("MainWindow", "Search by Code"))
        self.searchClientsByCityButton.setText(_translate("MainWindow", "Sort by City"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Clients"))
        self.searchItemByCodeButton.setText(_translate("MainWindow", "Search by Code"))
        self.searchItemsByCityButton.setText(_translate("MainWindow", "Empty"))
        self.searchItemByGroupButton.setText(_translate("MainWindow", "Search by Group"))
        self.searchForItemButton.setText(_translate("MainWindow", "Search by Name"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Items"))
        self.generateInvoiceButton.setText(_translate("MainWindow", "Generate Invoice"))
        self.nettoAmountLabel.setText(_translate("MainWindow", "Netto Amount:"))
        self.nettoAmountResultLabel.setText(_translate("MainWindow", "0"))
        self.totalAmountLabel.setText(_translate("MainWindow", "Total Amount:"))
        self.totalAmountResultLabel.setText(_translate("MainWindow", "0"))
        self.discountLabel.setText(_translate("MainWindow", "Upust:"))
        self.invoiceGenerationDateLabel.setText(_translate("MainWindow", "Data wystawienia:"))
        self.invoiceGenerationDateLabel_2.setText(_translate("MainWindow", "Data płatności:"))
        self.invoiceNumberLabel.setText(_translate("MainWindow", "Nr Faktury:"))
        self.invoiceSaleDateLabel_3.setText(_translate("MainWindow", "Data sprzedaży:"))
        self.invoicTypeLabel_2.setText(_translate("MainWindow", "Typ faktury"))
        self.invoiceTypeComboBox.setItemText(0, _translate("MainWindow", "Hurtowa"))
        self.invoiceTypeComboBox.setItemText(1, _translate("MainWindow", "Detaliczna"))
        self.invoiceTypeComboBox.setItemText(2, _translate("MainWindow", "Paragon"))
        self.invoiceTypeComboBox.setItemText(3, _translate("MainWindow", "Kupna"))
        self.invoicTypeLabel_3.setText(_translate("MainWindow", "Typ dokumentu:"))
        self.invoiceTypeComboBox_2.setItemText(0, _translate("MainWindow", "WZ"))
        self.invoiceTypeComboBox_2.setItemText(1, _translate("MainWindow", "PZ"))
        self.invoiceTypeComboBox_2.setItemText(2, _translate("MainWindow", "MZ"))
        self.warehouseSelectLabel_4.setText(_translate("MainWindow", "Magazyn:"))
        self.warehouseSelectComboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.warehouseSelectComboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.warehouseSelectComboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.warehouseSelectLabel_5.setText(_translate("MainWindow", "Zatwierdzone"))
        self.warehouseSelectComboBox_4.setItemText(0, _translate("MainWindow", "PRAWDA"))
        self.warehouseSelectComboBox_4.setItemText(1, _translate("MainWindow", "FAŁSZ"))
        self.priceTypeLabel.setText(_translate("MainWindow", "Rodzaj cen:"))
        self.priceTypeComboBox.setItemText(0, _translate("MainWindow", "Hurtowe"))
        self.priceTypeComboBox.setItemText(1, _translate("MainWindow", "Detaliczne"))
        self.paymentComboBox.setItemText(0, _translate("MainWindow", "Przelew"))
        self.paymentComboBox.setItemText(1, _translate("MainWindow", "Gotówka"))
        self.paymentComboBox.setItemText(2, _translate("MainWindow", "Rabat"))
        self.paymentLabel.setText(_translate("MainWindow", "Płatność:"))
        self.discountLabel_3.setText(_translate("MainWindow", "Nr księgowy:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sales Invoice "))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.sortInvoicesPushButton_5.setText(_translate("MainWindow", "Sort"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.documentsTypeComboBox.setItemText(0, _translate("MainWindow", "Invoices"))
        self.documentsTypeComboBox.setItemText(1, _translate("MainWindow", "Purchase Invoices"))
        self.documentsTypeComboBox.setItemText(2, _translate("MainWindow", "WZ"))
        self.documentsTypeComboBox.setItemText(3, _translate("MainWindow", "PZ"))
        self.documentsTypeComboBox.setItemText(4, _translate("MainWindow", "MZ"))
        self.documentsTypeComboBox.setItemText(5, _translate("MainWindow", "MM"))
        self.documentsTypeComboBox.setItemText(6, _translate("MainWindow", "RW"))
        self.documentsTypeComboBox.setItemText(7, _translate("MainWindow", "Settlement"))
        self.documentsTypeComboBox.setItemText(8, _translate("MainWindow", "Warehouse Cards"))
        self.documentsTypeComboBox.setItemText(9, _translate("MainWindow", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Show Invoices"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "WZ"))
        self.clientLabel_2.setText(_translate("MainWindow", "Client:"))
        self.clientResultLabel_2.setText(_translate("MainWindow", "Not selected yet"))
        self.searchForClientButton_2.setText(_translate("MainWindow", "Search by Name"))
        self.searchClientsByNIPButton_2.setText(_translate("MainWindow", "Search by NIP"))
        self.searchClientByCodeButton_2.setText(_translate("MainWindow", "Search by Code"))
        self.searchClientsByCityButton_2.setText(_translate("MainWindow", "Sort by City"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Clients"))
        self.searchItemByCodeButton_2.setText(_translate("MainWindow", "Search by Code"))
        self.searchItemsByCityButton_2.setText(_translate("MainWindow", "Empty"))
        self.searchItemByGroupButton_2.setText(_translate("MainWindow", "Search by Group"))
        self.searchForItemButton_2.setText(_translate("MainWindow", "Search by Name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Items"))
        self.generateInvoiceButton_2.setText(_translate("MainWindow", "Generate Invoice"))
        self.nettoAmountLabel_2.setText(_translate("MainWindow", "Netto Amount:"))
        self.nettoAmountResultLabel_2.setText(_translate("MainWindow", "0"))
        self.totalAmountLabel_2.setText(_translate("MainWindow", "Total Amount:"))
        self.totalAmountResultLabel_2.setText(_translate("MainWindow", "0"))
        self.discountLabel_2.setText(_translate("MainWindow", "Upust:"))
        self.invoiceGenerationDateLabel_3.setText(_translate("MainWindow", "Data wystawienia:"))
        self.invoiceGenerationDateLabel_4.setText(_translate("MainWindow", "Data płatności:"))
        self.invoiceNumberLabel_2.setText(_translate("MainWindow", "Nr Faktury:"))
        self.invoiceSaleDateLabel_4.setText(_translate("MainWindow", "Data sprzedaży:"))
        self.invoicTypeLabel_4.setText(_translate("MainWindow", "Typ faktury"))
        self.invoiceTypeComboBox_3.setItemText(0, _translate("MainWindow", "Hurtowa"))
        self.invoiceTypeComboBox_3.setItemText(1, _translate("MainWindow", "Paragon"))
        self.invoiceTypeComboBox_3.setItemText(2, _translate("MainWindow", "Kupna"))
        self.invoicTypeLabel_5.setText(_translate("MainWindow", "Typ dokumentu:"))
        self.invoiceTypeComboBox_4.setItemText(0, _translate("MainWindow", "WZ"))
        self.invoiceTypeComboBox_4.setItemText(1, _translate("MainWindow", "PZ"))
        self.invoiceTypeComboBox_4.setItemText(2, _translate("MainWindow", "MZ"))
        self.warehouseSelectLabel_6.setText(_translate("MainWindow", "Magazyn:"))
        self.warehouseSelectComboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.warehouseSelectComboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.warehouseSelectComboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.warehouseSelectLabel_7.setText(_translate("MainWindow", "Zatwierdzone"))
        self.warehouseSelectComboBox_6.setItemText(0, _translate("MainWindow", "PRAWDA"))
        self.warehouseSelectComboBox_6.setItemText(1, _translate("MainWindow", "FAŁSZ"))
        self.priceTypeLabel_2.setText(_translate("MainWindow", "Rodzaj cen:"))
        self.priceTypeComboBox_2.setItemText(0, _translate("MainWindow", "Hurtowe"))
        self.priceTypeComboBox_2.setItemText(1, _translate("MainWindow", "Detaliczne"))
        self.paymentComboBox_2.setItemText(0, _translate("MainWindow", "Przelew"))
        self.paymentComboBox_2.setItemText(1, _translate("MainWindow", "Gotówka"))
        self.paymentComboBox_2.setItemText(2, _translate("MainWindow", "Rabat"))
        self.paymentLabel_2.setText(_translate("MainWindow", "Płatność:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Purchase Invoice"))
        self.menuAbouy.setTitle(_translate("MainWindow", "About"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
