# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tryui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(210, 210))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.totalAmountResultLabel = QtWidgets.QLabel(self.tab)
        self.totalAmountResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountResultLabel.setObjectName("totalAmountResultLabel")
        self.gridLayout_3.addWidget(self.totalAmountResultLabel, 4, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/images/app.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableView_3 = QtWidgets.QTableView(self.frame)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_4.addWidget(self.tableView_3, 9, 2, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.clientLabel = QtWidgets.QLabel(self.frame_5)
        self.clientLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.clientLabel.setObjectName("clientLabel")
        self.gridLayout_5.addWidget(self.clientLabel, 2, 2, 1, 1)
        self.clientResultLabel = QtWidgets.QLabel(self.frame_5)
        self.clientResultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.clientResultLabel.setObjectName("clientResultLabel")
        self.gridLayout_5.addWidget(self.clientResultLabel, 3, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableView_2 = QtWidgets.QTableView(self.tab_6)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_9.addWidget(self.tableView_2, 0, 0, 1, 4)
        self.searchClientByCodeButton = QtWidgets.QPushButton(self.tab_6)
        self.searchClientByCodeButton.setObjectName("searchClientByCodeButton")
        self.gridLayout_9.addWidget(self.searchClientByCodeButton, 1, 0, 1, 1)
        self.searchClientsByNIPButton = QtWidgets.QPushButton(self.tab_6)
        self.searchClientsByNIPButton.setObjectName("searchClientsByNIPButton")
        self.gridLayout_9.addWidget(self.searchClientsByNIPButton, 1, 1, 1, 1)
        self.sortClientsByNameButton = QtWidgets.QPushButton(self.tab_6)
        self.sortClientsByNameButton.setObjectName("sortClientsByNameButton")
        self.gridLayout_9.addWidget(self.sortClientsByNameButton, 1, 2, 1, 1)
        self.searchForClientButton = QtWidgets.QPushButton(self.tab_6)
        self.searchForClientButton.setObjectName("searchForClientButton")
        self.gridLayout_9.addWidget(self.searchForClientButton, 1, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableView = QtWidgets.QTableView(self.tab_5)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setIconSize(QtCore.QSize(50, 50))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_10.addWidget(self.tableView, 0, 0, 1, 4)
        self.searchForItemButton = QtWidgets.QPushButton(self.tab_5)
        self.searchForItemButton.setObjectName("searchForItemButton")
        self.gridLayout_10.addWidget(self.searchForItemButton, 1, 0, 1, 1)
        self.searchItemByCodeButton = QtWidgets.QPushButton(self.tab_5)
        self.searchItemByCodeButton.setObjectName("searchItemByCodeButton")
        self.gridLayout_10.addWidget(self.searchItemByCodeButton, 1, 1, 1, 1)
        self.searchItemByGroupButton = QtWidgets.QPushButton(self.tab_5)
        self.searchItemByGroupButton.setObjectName("searchItemByGroupButton")
        self.gridLayout_10.addWidget(self.searchItemByGroupButton, 1, 2, 1, 1)
        self.sortItemsByNameButton = QtWidgets.QPushButton(self.tab_5)
        self.sortItemsByNameButton.setObjectName("sortItemsByNameButton")
        self.gridLayout_10.addWidget(self.sortItemsByNameButton, 1, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 0, 0, 2, 3)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 4, 4)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setObjectName("formLayout")
        self.invoiceNumberLabel = QtWidgets.QLabel(self.frame_4)
        self.invoiceNumberLabel.setObjectName("invoiceNumberLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.invoiceNumberLabel)
        self.invoicTypeLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.invoicTypeLabel_2.setObjectName("invoicTypeLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.invoicTypeLabel_2)
        self.invoiceNumberEdit = QtWidgets.QLineEdit(self.frame_4)
        self.invoiceNumberEdit.setObjectName("invoiceNumberEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.invoiceNumberEdit)
        self.invoiceTypeComboBox = QtWidgets.QComboBox(self.frame_4)
        self.invoiceTypeComboBox.setObjectName("invoiceTypeComboBox")
        self.invoiceTypeComboBox.addItem("")
        self.invoiceTypeComboBox.addItem("")
        self.invoiceTypeComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.invoiceTypeComboBox)
        self.paymentLabel = QtWidgets.QLabel(self.frame_4)
        self.paymentLabel.setObjectName("paymentLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.paymentLabel)
        self.invoicTypeLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.invoicTypeLabel_3.setObjectName("invoicTypeLabel_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.invoicTypeLabel_3)
        self.paymentComboBox = QtWidgets.QComboBox(self.frame_4)
        self.paymentComboBox.setObjectName("paymentComboBox")
        self.paymentComboBox.addItem("")
        self.paymentComboBox.addItem("")
        self.paymentComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.paymentComboBox)
        self.invoiceTypeComboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.invoiceTypeComboBox_2.setObjectName("invoiceTypeComboBox_2")
        self.invoiceTypeComboBox_2.addItem("")
        self.invoiceTypeComboBox_2.addItem("")
        self.invoiceTypeComboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.invoiceTypeComboBox_2)
        self.discountLabel = QtWidgets.QLabel(self.frame_4)
        self.discountLabel.setObjectName("discountLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.discountLabel)
        self.warehouseSelectLabel_4 = QtWidgets.QLabel(self.frame_4)
        self.warehouseSelectLabel_4.setObjectName("warehouseSelectLabel_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.warehouseSelectLabel_4)
        self.discountSpinBox = QtWidgets.QSpinBox(self.frame_4)
        self.discountSpinBox.setObjectName("discountSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.discountSpinBox)
        self.warehouseSelectComboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.warehouseSelectComboBox_3.setObjectName("warehouseSelectComboBox_3")
        self.warehouseSelectComboBox_3.addItem("")
        self.warehouseSelectComboBox_3.addItem("")
        self.warehouseSelectComboBox_3.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.warehouseSelectComboBox_3)
        self.invoiceGenerationDateLabel = QtWidgets.QLabel(self.frame_4)
        self.invoiceGenerationDateLabel.setObjectName("invoiceGenerationDateLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.invoiceGenerationDateLabel)
        self.warehouseSelectLabel_5 = QtWidgets.QLabel(self.frame_4)
        self.warehouseSelectLabel_5.setObjectName("warehouseSelectLabel_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.warehouseSelectLabel_5)
        self.invoiceGenerationDateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.invoiceGenerationDateEdit.setObjectName("invoiceGenerationDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.invoiceGenerationDateEdit)
        self.warehouseSelectComboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.warehouseSelectComboBox_4.setObjectName("warehouseSelectComboBox_4")
        self.warehouseSelectComboBox_4.addItem("")
        self.warehouseSelectComboBox_4.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.warehouseSelectComboBox_4)
        self.invoiceGenerationDateLabel_2 = QtWidgets.QLabel(self.frame_4)
        self.invoiceGenerationDateLabel_2.setObjectName("invoiceGenerationDateLabel_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.invoiceGenerationDateLabel_2)
        self.invoicePaymentDateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.invoicePaymentDateEdit.setDate(QtCore.QDate(2020, 1, 10))
        self.invoicePaymentDateEdit.setObjectName("invoicePaymentDateEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.invoicePaymentDateEdit)
        self.invoiceSaleDateLabel_3 = QtWidgets.QLabel(self.frame_4)
        self.invoiceSaleDateLabel_3.setObjectName("invoiceSaleDateLabel_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.invoiceSaleDateLabel_3)
        self.invoiceSaleDateEdit_2 = QtWidgets.QDateEdit(self.frame_4)
        self.invoiceSaleDateEdit_2.setDate(QtCore.QDate(2020, 1, 10))
        self.invoiceSaleDateEdit_2.setObjectName("invoiceSaleDateEdit_2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.invoiceSaleDateEdit_2)
        self.priceTypeLabel = QtWidgets.QLabel(self.frame_4)
        self.priceTypeLabel.setObjectName("priceTypeLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.priceTypeLabel)
        self.priceTypeComboBox = QtWidgets.QComboBox(self.frame_4)
        self.priceTypeComboBox.setObjectName("priceTypeComboBox")
        self.priceTypeComboBox.addItem("")
        self.priceTypeComboBox.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.priceTypeComboBox)
        self.gridLayout_4.addWidget(self.frame_4, 6, 0, 4, 2)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.generateInvoiceButton = QtWidgets.QPushButton(self.tab)
        self.generateInvoiceButton.setObjectName("generateInvoiceButton")
        self.gridLayout_3.addWidget(self.generateInvoiceButton, 5, 0, 1, 1)
        self.nettoAmountLabel = QtWidgets.QLabel(self.tab)
        self.nettoAmountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountLabel.setObjectName("nettoAmountLabel")
        self.gridLayout_3.addWidget(self.nettoAmountLabel, 1, 0, 1, 1)
        self.totalAmountLabel = QtWidgets.QLabel(self.tab)
        self.totalAmountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalAmountLabel.setObjectName("totalAmountLabel")
        self.gridLayout_3.addWidget(self.totalAmountLabel, 3, 0, 1, 1)
        self.nettoAmountResultLabel = QtWidgets.QLabel(self.tab)
        self.nettoAmountResultLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nettoAmountResultLabel.setObjectName("nettoAmountResultLabel")
        self.gridLayout_3.addWidget(self.nettoAmountResultLabel, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.sortInvoicesPushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.sortInvoicesPushButton_5.setObjectName("sortInvoicesPushButton_5")
        self.gridLayout_7.addWidget(self.sortInvoicesPushButton_5, 2, 0, 1, 1)
        self.tableView_4 = QtWidgets.QTableView(self.frame_3)
        self.tableView_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_4.setIconSize(QtCore.QSize(50, 50))
        self.tableView_4.setSortingEnabled(True)
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_4.horizontalHeader().setStretchLastSection(True)
        self.tableView_4.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_7.addWidget(self.tableView_4, 1, 0, 1, 4)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.documentsTypeComboBox = QtWidgets.QComboBox(self.frame_3)
        self.documentsTypeComboBox.setObjectName("documentsTypeComboBox")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.documentsTypeComboBox.addItem("")
        self.gridLayout_7.addWidget(self.documentsTypeComboBox, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbouy = QtWidgets.QMenu(self.menubar)
        self.menuAbouy.setObjectName("menuAbouy")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuAbouy.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.totalAmountResultLabel.setText(_translate("MainWindow", "0"))
        self.clientLabel.setText(_translate("MainWindow", "Client:"))
        self.clientResultLabel.setText(_translate("MainWindow", "Not selected yet"))
        self.searchClientByCodeButton.setText(_translate("MainWindow", "Search by Code"))
        self.searchClientsByNIPButton.setText(_translate("MainWindow", "Search by NIP"))
        self.sortClientsByNameButton.setText(_translate("MainWindow", "Sort by name"))
        self.searchForClientButton.setText(_translate("MainWindow", "Search For Client"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Clients"))
        self.searchForItemButton.setText(_translate("MainWindow", "Search by Name"))
        self.searchItemByCodeButton.setText(_translate("MainWindow", "Search by Code"))
        self.searchItemByGroupButton.setText(_translate("MainWindow", "Search by Group"))
        self.sortItemsByNameButton.setText(_translate("MainWindow", "Sort by Name"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Items"))
        self.invoiceNumberLabel.setText(_translate("MainWindow", "Nr Faktury:"))
        self.invoicTypeLabel_2.setText(_translate("MainWindow", "Typ faktury"))
        self.invoiceTypeComboBox.setItemText(0, _translate("MainWindow", "Hurtowa"))
        self.invoiceTypeComboBox.setItemText(1, _translate("MainWindow", "Paragon"))
        self.invoiceTypeComboBox.setItemText(2, _translate("MainWindow", "Kupna"))
        self.paymentLabel.setText(_translate("MainWindow", "Płatność:"))
        self.invoicTypeLabel_3.setText(_translate("MainWindow", "Typ dokumentu:"))
        self.paymentComboBox.setItemText(0, _translate("MainWindow", "Przelew"))
        self.paymentComboBox.setItemText(1, _translate("MainWindow", "Gotówka"))
        self.paymentComboBox.setItemText(2, _translate("MainWindow", "Rabat"))
        self.invoiceTypeComboBox_2.setItemText(0, _translate("MainWindow", "WZ"))
        self.invoiceTypeComboBox_2.setItemText(1, _translate("MainWindow", "PZ"))
        self.invoiceTypeComboBox_2.setItemText(2, _translate("MainWindow", "MZ"))
        self.discountLabel.setText(_translate("MainWindow", "Upust:"))
        self.warehouseSelectLabel_4.setText(_translate("MainWindow", "Magazyn:"))
        self.warehouseSelectComboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.warehouseSelectComboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.warehouseSelectComboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.invoiceGenerationDateLabel.setText(_translate("MainWindow", "Data wystawienia:"))
        self.warehouseSelectLabel_5.setText(_translate("MainWindow", "Zatwierdzone"))
        self.warehouseSelectComboBox_4.setItemText(0, _translate("MainWindow", "PRAWDA"))
        self.warehouseSelectComboBox_4.setItemText(1, _translate("MainWindow", "FAŁSZ"))
        self.invoiceGenerationDateLabel_2.setText(_translate("MainWindow", "Data płatności:"))
        self.invoiceSaleDateLabel_3.setText(_translate("MainWindow", "Data sprzedaży:"))
        self.priceTypeLabel.setText(_translate("MainWindow", "Rodzaj cen:"))
        self.priceTypeComboBox.setItemText(0, _translate("MainWindow", "Hurtowe"))
        self.priceTypeComboBox.setItemText(1, _translate("MainWindow", "Detaliczne"))
        self.label_2.setText(_translate("MainWindow", "Invoice App"))
        self.generateInvoiceButton.setText(_translate("MainWindow", "Generate Invoice"))
        self.nettoAmountLabel.setText(_translate("MainWindow", "Netto Amount:"))
        self.totalAmountLabel.setText(_translate("MainWindow", "Total Amount:"))
        self.nettoAmountResultLabel.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sales Invoice "))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.sortInvoicesPushButton_5.setText(_translate("MainWindow", "Sort"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.documentsTypeComboBox.setItemText(0, _translate("MainWindow", "Invoices"))
        self.documentsTypeComboBox.setItemText(1, _translate("MainWindow", "Purchase Invoices"))
        self.documentsTypeComboBox.setItemText(2, _translate("MainWindow", "WZ"))
        self.documentsTypeComboBox.setItemText(3, _translate("MainWindow", "PZ"))
        self.documentsTypeComboBox.setItemText(4, _translate("MainWindow", "MZ"))
        self.documentsTypeComboBox.setItemText(5, _translate("MainWindow", "MM"))
        self.documentsTypeComboBox.setItemText(6, _translate("MainWindow", "RW"))
        self.documentsTypeComboBox.setItemText(7, _translate("MainWindow", "Settlement"))
        self.documentsTypeComboBox.setItemText(8, _translate("MainWindow", "Warehouse Cards"))
        self.documentsTypeComboBox.setItemText(9, _translate("MainWindow", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Show Invoices"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "WZ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.menuAbouy.setTitle(_translate("MainWindow", "About"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
